export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_BY_ORIGIN = 'FETCH_PRODUCT_BY_ORIGIN';
export const ADD_USER = 'ADD_USER';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_PRODUCT_BY_CATEGORY = 'FETCH_PRODUCT_BY_CATEGORY';